# ==========================================
# CONFIGURAÇÕES DO POSTGRESQL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca_db
spring.datasource.username=postgres
spring.datasource.password=Books..
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ==========================================
# Atualiza as tabelas automaticamente quando você mudar o código Java
spring.jpa.hibernate.ddl-auto=update

# Mostra no console do VS Code o SQL que o Spring está executando (ótimo para estudar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true