# ==========================================
# CONFIGURAÇÕES DO POSTGRESQL (LOCAL - DESATIVADO)
# ==========================================
# spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca_db
# spring.datasource.username=postgres
# spring.datasource.password=527463
# spring.datasource.driver-class-name=org.postgresql.Driver

# Porta em que a API vai rodar
server.port=8888

# ==========================================
# CONEXÃO COM O SUPABASE (PRODUÇÃO)
# ==========================================
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.tthflumzkuewvcaixnbo
spring.datasource.password=A@#TYTY45%%$
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURAÇÕES DO HIKARI (LIMITAÇÃO DO SUPABASE)
# ==========================================
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000

# ==========================================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ==========================================
# Atualiza as tabelas automaticamente quando você mudar o código Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostra no console do VS Code o SQL que o Spring está executando
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true